version: "3.9"

services:

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse_proxy/conf.d:/etc/nginx/conf.d
    ports:
        - "80:80"

  site1:
    build: site1
    expose:
      - 80

  site2:
    build: site2
    expose:
      - 80
